-- Cadastro Municipal de Artistas - Banco de Dados
-- Execute este script no SQL Editor do Supabase

DROP TABLE IF EXISTS artistas CASCADE;

CREATE TABLE artistas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  contato TEXT,
  cidade TEXT DEFAULT 'Bagé',
  area_atuacao TEXT NOT NULL,
  bio TEXT,
  foto_url TEXT,
  instagram TEXT,
  site TEXT,
  status TEXT DEFAULT 'Pendente' CHECK (status IN ('Pendente', 'Aprovado', 'Rejeitado')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Módulo de Feedback do Público
DROP TABLE IF EXISTS feedbacks CASCADE;

CREATE TABLE feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT,
  email TEXT,
  tipo TEXT DEFAULT 'Sugestão' CHECK (tipo IN ('Elogio', 'Sugestão', 'Crítica', 'Outro')),
  nota INTEGER CHECK (nota BETWEEN 1 AND 5),
  mensagem TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Políticas de Acesso (Desativa RLS para permitir inserção/leitura via API)
ALTER TABLE artistas DISABLE ROW LEVEL SECURITY;
ALTER TABLE feedbacks DISABLE ROW LEVEL SECURITY;

-- Dados de exemplo para teste
INSERT INTO artistas (nome, email, contato, cidade, area_atuacao, bio, instagram, status) VALUES
('Maria dos Santos', 'maria@email.com', '(53) 99999-0001', 'Bagé', 'Música', 'Cantora e compositora gaúcha com mais de 10 anos de carreira. Especialista em música popular brasileira e folclore do Pampa.', '@mariadossantos', 'Aprovado'),
('Carlos Pintura', 'carlos@email.com', '(53) 99999-0002', 'Bagé', 'Artes Visuais', 'Artista plástico com obras expostas em galerias de Porto Alegre, Pelotas e Bagé. Trabalha com acrílica, óleo e aquarela.', '@carlospintura', 'Aprovado'),
('Ana Fotografias', 'ana@email.com', '(53) 99999-0003', 'Bagé', 'Fotografia', 'Fotógrafa especializada em fotografia documental e retratos. Registra a cultura e o cotidiano da fronteira.', '@anafotografias', 'Pendente');

-- Feedbacks de exemplo para teste
INSERT INTO feedbacks (nome, email, tipo, nota, mensagem) VALUES
('Pedro Souza', 'pedro@email.com', 'Sugestão', 5, 'A plataforma ficou excelente! Sugiro adicionar upload de fotos diretamente do dispositivo em vez de apenas link.'),
('Mariana Lima', 'mariana@email.com', 'Elogio', 5, 'Parabéns pela iniciativa! Consegui encontrar vários artistas locais incríveis.'),
('João Pereira', NULL, 'Crítica', 3, 'O formulário de cadastro é extenso. Alguns campos poderiam ser opcionais para facilitar.');
